### ISSUE TITLE
How to obtain npy files required for test?

### ISSUE THREAD

**Issue by mariolew** [facebookresearch/body2hands#1]
I'd like to test some custom videos. How to obtain npy files required for test?

**Comment by ChawDoe** [comment]
I have the same question. Have you solved it?

**Comment by ChawDoe** [comment]
> I'd like to test some custom videos. How to obtain npy files required for test?

Hi. Do you have any idea?

**Comment by evonneng** [comment]
Thank yall for the interest! I updated the README to go through how to obtain the npy files.
https://github.com/facebookresearch/body2hands#using-your-own-data-for-train

Essentially, the .npy files are a consolidation of all the per-frame outputs from MTC (%04.txt) or resnet features into one large BxTxF matrix.

**Comment by YananSunn** [comment]
> Thank yall for the interest! I updated the README to go through how to obtain the npy files. https://github.com/facebookresearch/body2hands#using-your-own-data-for-train
> 
> Essentially, the .npy files are a consolidation of all the per-frame outputs from MTC (%04.txt) or resnet features into one large BxTxF matrix.

Hi, I'm trying to use my own data to test, but still confused about how to generate full_resnet.npy. Could you please explain it with more details? (Maybe with some codes if necessary.) Thanks a lot!
