### ISSUE TITLE
Missing Supp.(supplementary) in paper

### ISSUE THREAD

**Issue by HanXiaoyou** [facebookresearch/body2hands#10]
How can I find the Supp.  metioned in the paper? I can not find it neither on the [CVF page](https://openaccess.thecvf.com/CVPR2021?day=2021-06-24) nor [project page](http://people.eecs.berkeley.edu/~evonne_ng/projects/body2hands/).

**Comment by evonneng** [comment]
Hello! Thank you for your interest and pointing this out! Link for it can now be found here: https://people.eecs.berkeley.edu/~evonne_ng/projects/body2hands/body2hands_supp.pdf
