### ISSUE TITLE
why body poses need to be multiplied by -1?

### ISSUE THREAD

**Issue by shaoguowen** [facebookresearch/body2hands#8]
https://github.com/facebookresearch/body2hands/blob/0eba438b4343604548120bdb03c7e1cb2b08bcd6/smplx_plugin/demo.py#L138

**Comment by evonneng** [comment]
Great question! This is due to back-compatibility with the Franklin model (since this is what we trained body2hands with). 
In Franklin, the body is essentially flipped w.r.t. the SMPL model.
