### ISSUE TITLE
Indexes of arm joints in SMPL is not correct?

### ISSUE THREAD

**Issue by shaoguowen** [facebookresearch/body2hands#9]
https://github.com/facebookresearch/body2hands/blob/0eba438b4343604548120bdb03c7e1cb2b08bcd6/utils/load_utils.py#L21

**Comment by evonneng** [comment]
Thank you for the catch!! You are correct, this is for MTC. The patch can be found here: https://github.com/facebookresearch/body2hands/blob/main/smplx_plugin/demo.py
